---
title: "Vocal activity and breeding asynchrony Colombia"
author: "Miguel Moreno-Palacios, Orlando Acevedo-Charry, & Carlos Daniel Cadena"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Packages

```{r}
library(tidyverse)
```

## Sampling figure


```{r sampling figure}
sampling <- read_csv("data/All_recordings_ARBIMON.csv")

sampling |> 
  filter(site != "Unibague") |>
  mutate(year = paste0("20",year),
         date = as.Date.character(paste0(year, "-", month, "-", day)),
         MM_YY = cut(date, breaks = "month")) |>
  group_by(site, MM_YY) |>
  summarise(n_recordings = n()) |> 
  ungroup() |>
  ggplot(aes(x = as.Date.factor(MM_YY), 
             y = factor(site,
                        levels = c("GAIA",
                                   "PRIMAVERA",
                                   "DOIMA",
                                   "POTRERILLO")))) +
    geom_tile(aes(fill = n_recordings,
                  color = n_recordings),
              alpha = 0.9) +
    scale_y_discrete(labels = c("Gaia (1378m)",
                                "Primavera (995m)",
                                "Doima (615m)",
                                "Potrerillo (440m)"))+
    scale_x_date(limits = c(as.Date.character("2022-05-15"),
                            as.Date.character("2023-09-15")),
                 date_labels = "%b\n%Y",
                 date_breaks = "2 months",
                 expand = c(0,0))+
    scale_fill_viridis_c() +
    scale_color_viridis_c() +
    labs(x = "Date (month and year)",
         y = "Site",
         fill = "# recordings",
         color = "# recordings")+
    theme_classic()

```

## Overall acoustic activity

Soundscapes: DOI_DOI, PRIM_DOI, POT_DOI, GAIA_DOI

```{r soundscapes}
Potrerillo_doy <- read_csv("data/POT_DOI.csv") |>
  mutate(site = "Potrerillo (440m)")
Doima_doy <- read_csv("data/DOI_DOI.csv") |>
  mutate(site = "Doima (615m)")
Primavera_doy <- read_csv("data/PRIM_DOI.csv")|>
  mutate(site = "Primavera (995m)")
Gaia_doy <- read_csv("data/GAIA_DOI.csv")|>
  mutate(site = "Gaia (1378m)")

rbind(Potrerillo_doy,
                     Doima_doy,
                     Primavera_doy,
                     Gaia_doy) |>
  pivot_longer(!c("freq-min",
                  "freq-max",
                  "site"),
               names_to = "Day of year",
               values_to = "Z") |> 
  mutate(`Day of year` = as.numeric(`Day of year`)) |> 
  ggplot(aes(x = (`Day of year`),
             y = `freq-max`/1000, 
             fill = log(Z))) +
  geom_tile() +
  facet_wrap(~factor(site, levels = c("Potrerillo (440m)",
                                      "Doima (615m)",
                                      "Primavera (995m)",
                                      "Gaia (1378m)")),
             ncol = 1) +
  scale_fill_viridis_c()+
  scale_x_continuous(expand = c(0,0))+
  scale_y_continuous(limits = c(0,13.5),
                     expand = c(0,0),
                     breaks = seq(0,13,4))+
  labs(x = "Day of year",
       y = "Frequency (kHz)")+
  theme_classic()

```

## Species-specific acoustic activity

Turdus leucomelas

```{r Turdus}

# have a sequence of weeks to recreate the dates
weekly_dates <- seq.Date(from = as.Date("2022-06-06"), to = as.Date("2023-09-09"), by = "week")

# Create a reference dataframe with Time.t and dates
time_reference <- data.frame(
  Time.t = 23:(23 + length(weekly_dates) - 1),
  date_filled = weekly_dates
)


turdus <- read_csv("data/occupancy-Turdus_leucomelas-43.csv") |>
  filter(site != "Unibague") |>
  mutate(site = ifelse(site == "DOIMA", "Doima (615m)",
                ifelse(site == "GAIA", "Gaia (1378m)",
                ifelse(site == "POTRERILLO", "Potrerillo (440m)",
                ifelse(site == "PRIMAVERA", "Primavera (995m)",
                       "OTHER")))))


turdus |>
  pivot_longer(!c(site, siteId),
               names_to = "date",
               values_to = "detection") |> 
  mutate(day_samp = as.Date.character(date, format = "%Y/%m/%d"),
         Year = year(day_samp),
         Month = month(day_samp),
         Week = week(day_samp),
         Time.t = case_when(Year == 2022 ~ Week,
                            Year > 2022 ~ Week+(52*(Year-2022)))) |>
  drop_na(detection) |>
  left_join(time_reference, by = "Time.t") |>
  group_by(site, date_filled) |>
  summarise(n_recordings = n(),
            n_detections = sum(detection),
            activity = (n_detections/n_recordings)*100) |>
  ggplot(aes(x = date_filled, y = activity)) +
    geom_point() +
    facet_wrap(~factor(site, levels = c("Potrerillo (440m)",
                                      "Doima (615m)",
                                      "Primavera (995m)",
                                      "Gaia (1378m)")),
               ncol = 1) +
  labs(x = "Date",
       y = "Weekly activity") +
  theme_classic()

```

